sudo: required
services:
    - docker

before_install:
    - docker build -t gabrielfernando033/react-app -f Dockerfile.dev .

script:
    - docker run -e CI=true gabrielfernando033/react-app npm run test

deploy:
    provider: elasticbeanstalk
    region: ""
    app: ""
    env: ""
    bucket_name: ""
    bucket_path: ""
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY