sudo: required
services:
    - docker

before_install:
    - docker build -t gabrielfernando033/react-app -f Dockerfile.dev .

script:
    - docker run gabrielfernando033/react-app npm run test -- --coverage